/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class AssetManagerFunds extends Contract {
  functions: {
    viewBalance(
      _assetAddress: string,
      _assetManager: string
    ): Promise<BigNumber>;

    viewAmountOwed(
      _assetAddress: string,
      _assetManager: string
    ): Promise<BigNumber>;

    withdraw(
      _assetAddress: string,
      _assetManager: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    retrieveAssetManagerTokens(
      _assetAddress: (string)[],
      _assetManager: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    retrieveAssetManagerETH(
      _assetAddress: (string)[],
      _assetManager: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    destroy(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    database(): Promise<string>;
    events(): Promise<string>;
  };
  filters: {};
}
