/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class AssetGenerator extends Contract {
  functions: {
    createAsset(
      _tokenURI: string,
      _assetManager: string,
      _tokenHolders: (string)[],
      _amount: (number | string | BigNumber)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    createTradeableAsset(
      _tokenURI: string,
      _assetManager: string,
      _tokenHolders: (string)[],
      _amount: (number | string | BigNumber)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    destroy(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };
  filters: {};
}
