/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class CrowdsaleReserve extends Contract {
  functions: {
    issueETH(
      _receiver: string,
      _amount: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    receiveETH(
      _payer: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    refundETHAsset(
      _asset: string,
      _amount: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    issueERC20(
      _receiver: string,
      _amount: number | string | BigNumber,
      _tokenAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    requestERC20(
      _payer: string,
      _amount: number | string | BigNumber,
      _tokenAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    approveERC20(
      _receiver: string,
      _amount: number | string | BigNumber,
      _tokenAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    refundERC20Asset(
      _asset: string,
      _amount: number | string | BigNumber,
      _tokenAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };
  filters: {};
}
