/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class CrowdsaleERC20 extends Contract {
  functions: {
    buyAssetOrderERC20(
      _assetAddress: string,
      _investor: string,
      _amount: number | string | BigNumber,
      _paymentToken: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    payoutERC20(
      _assetAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    refund(
      _assetAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    recoverTokens(
      _erc20Token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    destroy(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };
  filters: {
    Convert(token: null, change: null, investment: null): EventFilter;

    EtherReceived(sender: null, amount: null): EventFilter;
  };
}
