/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class CrowdsaleGeneratorETH extends Contract {
  functions: {
    createAssetOrderETH(
      _assetURI: string,
      _assetManager: string,
      _operatorID: string,
      _fundingLength: number | string | BigNumber,
      _startTime: number | string | BigNumber,
      _amountToRaise: number | string | BigNumber,
      _assetManagerPerc: number | string | BigNumber,
      _escrow: number | string | BigNumber,
      _paymentToken: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    destroy(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    database(): Promise<string>;
    events(): Promise<string>;
  };
  filters: {};
}
