/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class ERC20Burner extends Contract {
  functions: {
    burn(
      _tokenHolder: string,
      _amount: number | string | BigNumber,
      _burnToken: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setFee(
      _methodID: string,
      _contractAddress: string,
      _amount: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    destroy(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    database(): Promise<string>;
    events(): Promise<string>;
    token(): Promise<string>;
  };
  filters: {
    LogMYBBurned(
      _tokenHolder: null,
      _burningContract: null,
      _amount: null
    ): EventFilter;

    LogFeeAdded(
      _contractAddress: string | null,
      _methodID: null,
      _amount: null
    ): EventFilter;

    LogTokenAddress(tokenAddress: null): EventFilter;

    Trade(
      src: null,
      amount: null,
      dest: null,
      receiver: null,
      max: null,
      minRate: null,
      walletID: null
    ): EventFilter;

    EtherReceived(sender: null, amount: null): EventFilter;
  };
}
